### ISSUE TITLE
ErrorException: PDO::prepare(): MySQL server has gone away

### ISSUE THREAD

**Issue by iPurpl3x** [FriendsOfFlarum/sentry#15]
I found this error in my logs, sorry I have no idea how to reproduce...
Flarum : beta.13
fof/sentry: 0.5.0

```log
production.ERROR: ErrorException: PDO::prepare(): MySQL server has gone away in /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78
Stack trace:
#0 [internal function]: FoF\Sentry\SentryServiceProvider->handleError(2, 'PDO::prepare():...', '/opt/flarum/ven...', 78, Array)
#1 /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(78): PDO->prepare('select * from `...', Array)
#2 /opt/flarum/vendor/illuminate/database/Connection.php(326): Doctrine\DBAL\Driver\PDOConnection->prepare('select * from `...')
#3 /opt/flarum/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#4 /opt/flarum/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#5 /opt/flarum/vendor/illuminate/database/Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#6 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2095): Illuminate\Database\Connection->select('select * from `...', Array, false)
#7 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2083): Illuminate\Database\Query\Builder->runSelect()
#8 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2569): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#9 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2084): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#10 /opt/flarum/vendor/illuminate/database/Eloquent/Builder.php(519): Illuminate\Database\Query\Builder->get(Array)
#11 /opt/flarum/vendor/illuminate/database/Eloquent/Builder.php(503): Illuminate\Database\Eloquent\Builder->getModels(Array)
#12 /opt/flarum/vendor/illuminate/database/Concerns/BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#13 /opt/flarum/vendor/illuminate/database/Eloquent/Builder.php(448): Illuminate\Database\Eloquent\Builder->first(Array)
#14 /opt/flarum/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\Database\Eloquent\Builder->firstOrFail()
#15 /opt/flarum/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(55): Flarum\Subscriptions\Job\SendReplyNotification->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#16 /opt/flarum/vendor/illuminate/queue/SerializesModels.php(45): Flarum\Subscriptions\Job\SendReplyNotification->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#17 [internal function]: Flarum\Subscriptions\Job\SendReplyNotification->__wakeup()
#18 /opt/flarum/vendor/illuminate/queue/CallQueuedHandler.php(42): unserialize('O:46:"Flarum\\Su...')
#19 /opt/flarum/vendor/illuminate/queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#20 /opt/flarum/vendor/illuminate/queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#21 /opt/flarum/vendor/illuminate/queue/Worker.php(277): Illuminate\Queue\Worker->process(NULL, Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#22 /opt/flarum/vendor/illuminate/queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), NULL, Object(Illuminate\Queue\WorkerOptions))
#23 /opt/flarum/vendor/illuminate/queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon(NULL, 'default', Object(Illuminate\Queue\WorkerOptions))
#24 /opt/flarum/vendor/illuminate/queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'default')
#25 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#26 /opt/flarum/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#27 /opt/flarum/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 /opt/flarum/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Flarum\Foundation\Application), Array, Object(Closure))
#29 /opt/flarum/vendor/illuminate/container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Flarum\Foundation\Application), Array, Array, NULL)
#30 /opt/flarum/vendor/illuminate/console/Command.php(183): Illuminate\Container\Container->call(Array)
#31 /opt/flarum/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 /opt/flarum/vendor/illuminate/console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#33 /opt/flarum/vendor/symfony/console/Application.php(1027): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /opt/flarum/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /opt/flarum/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /opt/flarum/vendor/flarum/core/src/Console/Server.php(44): Symfony\Component\Console\Application->run()
#37 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#38 {main}
```

**Comment by clarkwinkelmann** [comment]
That's a MySQL issue. The server might have been restarting while someone accessed Flarum.

If it happened only once, it's probably no cause for worry. If it happens regularly, something might be wrong with the setup.

I don't think there's anything we can do here. Feel free to re-open if you have additional details.
