### ISSUE TITLE
Error 500 in `app.data.apiDocument` after clearing cache

### ISSUE THREAD

**Issue by iPurpl3x** [FriendsOfFlarum/sentry#19]
## Bug Report

**Current Behavior**
Error 500 in `app.data.apiDocument` after clearing cache from admin dashboard.

**Steps to Reproduce**
I don't know. Disabling and re-enabling fof/sentry apparently fixed the issue for me. Hopefully it won't come up again! 

**Expected Behavior**
No error

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.0.1
- Website URL: https://community.upc.ch/
- Webserver: nginx
- PHP version: 8.0.9
- Browser: all

```
/opt/flarum # php flarum info
Flarum core 1.0.4
PHP version: 8.0.9
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, json, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, gmp, mbstring, openssl, PDO, standard, tokenizer, xmlwriter, zip, exif, mysqlnd, Phar, pdo_mysql, igbinary, redis, Zend OPcache
+-----------------------------------+--------------+------------------------------------------+
| Flarum Extensions                 |              |                                          |
+-----------------------------------+--------------+------------------------------------------+
| ID                                | Version      | Commit                                   |
+-----------------------------------+--------------+------------------------------------------+
| flarum-tags                       | v1.0.3       |                                          |
| flarum-flags                      | v1.0.0       |                                          |
| fof-discussion-language           | 1.1.2        |                                          |
| flarum-lock                       | v1.0.0       |                                          |
| v17development-seo                | v1.8.0       |                                          |
| fof-linguist                      | 1.0.0        |                                          |
| fof-impersonate                   | 1.0.0        |                                          |
| flarum-subscriptions              | v1.0.0       |                                          |
| flarum-approval                   | v1.0.0       |                                          |
| flarum-suspend                    | v1.0.0       |                                          |
| v17development-blog               | 0.4.2        |                                          |
| ianm-html-head                    | 1.0.0        |                                          |
| glowingblue-core                  | 1.0.1        |                                          |
| fof-terms                         | 1.0.0        |                                          |
| fof-links                         | 1.0.0        |                                          |
| flarum-markdown                   | v1.0.1       |                                          |
| flarum-lang-french                | v3.0.0       |                                          |
| flarum-lang-italian               | 1.0.23       |                                          |
| glowingblue-typeform              | 1.0.0        |                                          |
| fof-username-request              | 1.0.0        |                                          |
| fof-upload                        | 1.0.2        |                                          |
| fof-subscribed                    | 1.0.0        |                                          |
| fof-reactions                     | 1.0.0        |                                          |
| fof-moderator-notes               | 1.0.0        |                                          |
| fof-frontpage                     | 1.0.0        |                                          |
| fof-follow-tags                   | 1.0.1        |                                          |
| fof-drafts                        | 1.0.1        |                                          |
| fof-byobu                         | 1.0.0-beta.7 |                                          |
| fof-best-answer                   | 1.0.1        |                                          |
| flarum-mentions                   | v1.0.0       |                                          |
| flarum-likes                      | v1.0.0       |                                          |
| flarum-lang-english               | v1.0.0       |                                          |
| extiverse-mercury                 | 0.1.3        |                                          |
| clarkwinkelmann-mailing           | 1.0.0        |                                          |
| glowingblue-upc                   | 1.0.0        |                                          |
| fof-sentry                        | 1.0.1        |                                          |
| glowingblue-localizd              | 1.0.1        |                                          |
| askvortsov-rich-text              | v2.0.3.1     | 8d046610ff961649df87e4a16201275affc0a37b |
| fof-profile-image-crop            | 1.0.0        |                                          |
| glowingblue-upc-de                | 1.0.0        |                                          |
| glowingblue-upc-fr                | 1.0.0        |                                          |
| glowingblue-redis-setup           | 1.0.3        |                                          |
| flarum-bbcode                     | v1.0.0       |                                          |
| flarum-emoji                      | v1.0.0       |                                          |
| flarum-sticky                     | v1.0.0       |                                          |
| fof-user-bio                      | 1.0.0        |                                          |
| fof-default-user-preferences      | 1.0.0        |                                          |
| fof-formatting                    | 1.0.0        |                                          |
| glowingblue-user-activity         | 1.0.0        |                                          |
| fof-sitemap                       | 1.0.0        |                                          |
| fof-polls                         | 1.0.3        |                                          |
| fof-pages                         | 1.0.1        |                                          |
| fof-merge-discussions             | 1.0.0        |                                          |
| fof-split                         | 1.0.0        |                                          |
| flarum-statistics                 | v1.0.0       |                                          |
| flarumite-simple-discussion-views | 1.0.3        |                                          |
| fof-forum-statistics-widget       | 1.0.0        |                                          |
| askvortsov-pwa                    | v3.0.3       |                                          |
| fof-analytics                     | 1.0.0        |                                          |
| clarkwinkelmann-emojionearea      | 1.0.0        |                                          |
| clarkwinkelmann-bookmarks         | 1.0.0        |                                          |
| sycho-profile-cover               | v1.3.0       |                                          |
| clarkwinkelmann-author-change     | 1.0.1        |                                          |
| flarum-lang-german                | 1.1.4        |                                          |
| glowingblue-upc-it                | 1.0.0        |                                          |
| glowingblue-upc-en                | 1.0.0        |                                          |
| zerosonesfun-direct-links         | 2.2          |                                          |
| glowingblue-password-strength     | 3.0.0        |                                          |
| fof-user-directory                | 1.0.2        |                                          |
+-----------------------------------+--------------+------------------------------------------+
Base URL: https://community.upc.ch
Installation path: /opt/flarum
Debug mode: off
```

**Possible solution(s)**

**Additional Context**

## Error logs (with only the interesting part)

```log
[2021-08-19 11:05:59] flarum.ERROR: ErrorException: Undefined property: stdClass::$data in /opt/flarum/storage/views/d317b682fb92ea3d63f086c5ad8b7518f6e17621.php:7
Stack trace:
#0 /opt/flarum/vendor/sentry/sentry/src/ErrorHandler.php(303): FoF\Sentry\SentryServiceProvider->handleError()
#1 /opt/flarum/storage/views/d317b682fb92ea3d63f086c5ad8b7518f6e17621.php(7): Sentry\ErrorHandler->handleError()
#2 /opt/flarum/vendor/illuminate/filesystem/Filesystem.php(107): require('...')
#3 /opt/flarum/vendor/illuminate/filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()

[2021-08-19 11:05:59] flarum.ERROR: ErrorException: foreach() argument must be of type array|object, null given in /opt/flarum/storage/views/d317b682fb92ea3d63f086c5ad8b7518f6e17621.php:7
Stack trace:
#0 /opt/flarum/vendor/sentry/sentry/src/ErrorHandler.php(303): FoF\Sentry\SentryServiceProvider->handleError()
#1 /opt/flarum/storage/views/d317b682fb92ea3d63f086c5ad8b7518f6e17621.php(7): Sentry\ErrorHandler->handleError()
#2 /opt/flarum/vendor/illuminate/filesystem/Filesystem.php(107): require('...')
#3 /opt/flarum/vendor/illuminate/filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
```

**Comment by dsevillamartin** [comment]
Hm those errors might be unrelated? Usually 500 in apiDocument doesn't get logged i think, might be wrong. But we'd still want to fix those.

**Comment by iPurpl3x** [comment]
@datitisev OK well I though it was related as I could solve the issue by disabling and re-enabling Sentry....

**Comment by dsevillamartin** [comment]
I don't know whether it is, but might want to look into it regardless.
